### ISSUE TITLE
cannot connect to mysql running in separate docker container

### ISSUE THREAD

**Issue by stuart-leitch** [claycephas/docker-flyway#1]
Hey @claycephas , I've been using your flyway image, but cannot get it to connect to a mysql db in another docker container.

I'm creating a mysql docker instance (see docker compose file below) and exposing port 3306.  I can connect to this from MySQL Workbench on my mac.  I can also run flyway migrations against it using a locally installed flyway instance.

When trying to use the dockerised flyway I get this error:

`Flyway 4.0.3 by Boxfuse
2016-09-14T22:04:23.396379229Z 
ERROR: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:3306/customer) for user 'root': Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused`

Simplest recreation looks like this:

`docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysql -e MYSQL_DATABASE=customer -d mysql:5.7
docker run -v $PWD/sql:/migrations claycephas/flyway -X clean migrate  -url=jdbc:mysql://localhost:3306/customer -locations=filesystem:/migrations -user=root -password=mysql`

Probably not an issue with the image as such, more likely user error.  Any assistance very gratefully received. 

EDIT: I've also installed MySQL locally.  Local Flywheel cheerfully migrates that, but dockerised flywheel has the same issue described above.

**Comment by supersonicclay** [comment]
Yes, this is just how docker works. `localhost` from your flyway container will refer to the container that flyway is running in, not your host, and not your mysql container.

You have a couple of options:
- Give your mysql container a name (using the `--name` option) and link your flyway container (using the `--link` option).

```
docker run --name db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysql -e MYSQL_DATABASE=customer -d mysql:5.7
docker run --link db -v $PWD/sql:/migrations claycephas/flyway -X clean migrate -url=jdbc:mysql://db:3306/customer -locations=filesystem:/migrations -user=root -password=mysql
```
- Give your mysql container a name (using the `--name` option) and connect both containers to the same network.

```
docker network create mynetwork
docker run --name db --network mynetwork -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mysql -e MYSQL_DATABASE=customer -d mysql:5.7
docker run --network mynetwork -v $PWD/sql:/migrations claycephas/flyway -X clean migrate -url=jdbc:mysql://db:3306/customer -locations=filesystem:/migrations -user=root -password=mysql
```
- Use [docker-compose](https://docs.docker.com/compose/) to simplify creating a network and linking containers.

**Comment by stuart-leitch** [comment]
Thanks for such a quick, helpful response.  I hadn't understood  localhost being container specific, so that helps.

I had been trying to do this with docker-compose, but thought getting it working without compose would be a good first step.  Having that working now, I'm still struggling with compose.  My yml is below, if you spot a glaring error, but I realise this is a docker connectivity thing, and nothing to do with your flyway image.

Thanks again!

[docker-compose.yml.txt](https://github.com/claycephas/docker-flyway/files/474249/docker-compose.yml.txt)

**Comment by stuart-leitch** [comment]
oh, wow....

I'm trying to migrate a db before the mysql service is ready!

D'Oh!
